export const zodiacSigns = [
    { sign: "Capricorn",    start: { day: 22, month: 12 }, end: { day: 19, month: 1 } },
    { sign: "Aquarius",     start: { day: 20, month: 1 },  end: { day: 18, month: 2 } },
    { sign: "Pisces",       start: { day: 19, month: 2 },  end: { day: 20, month: 3 } },
    { sign: "Aries",        start: { day: 21, month: 3 },  end: { day: 19, month: 4 } },
    { sign: "Taurus",       start: { day: 20, month: 4 },  end: { day: 20, month: 5 } },
    { sign: "Gemini",       start: { day: 21, month: 5 },  end: { day: 20, month: 6 } },
    { sign: "Cancer",       start: { day: 21, month: 6 },  end: { day: 22, month: 7 } },
    { sign: "Leo",          start: { day: 23, month: 7 },  end: { day: 22, month: 8 } },
    { sign: "Virgo",        start: { day: 23, month: 8 },  end: { day: 22, month: 9 } },
    { sign: "Libra",        start: { day: 23, month: 9 },  end: { day: 22, month: 10 } },
    { sign: "Scorpio",      start: { day: 23, month: 10 }, end: { day: 21, month: 11 } },
    { sign: "Sagittarius",  start: { day: 22, month: 11 }, end: { day: 21, month: 12 } }
];

export const zodiacTable = {
    "Aries": {
        "Aries": { compatibility: "High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Average", strengths: ["Determined", "Patient"], weaknesses: ["Stubborn", "Possessive"] },
        "Gemini": { compatibility: "High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Low", strengths: ["Loyal", "Protective"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Very High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Average", strengths: ["Practical", "Analytical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Very High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Average", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Average", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Taurus": {
        "Aries": { compatibility: "Average", strengths: ["Determined", "Patient"], weaknesses: ["Stubborn", "Possessive"] },
        "Taurus": { compatibility: "Very High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Low", strengths: ["Adaptable", "Outgoing"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "High", strengths: ["Loyal", "Emotional"], weaknesses: ["Moody", "Clingy"] },
        "Leo": { compatibility: "Average", strengths: ["Generous", "Creative"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Very High", strengths: ["Analytical", "Practical"], weaknesses: ["Overly Critical", "Worrying"] },
        "Libra": { compatibility: "Average", strengths: ["Diplomatic", "Charming"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "High", strengths: ["Passionate", "Loyal"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Low", strengths: ["Adventurous", "Optimistic"], weaknesses: ["Impatient", "Blunt"] },
        "Capricorn": { compatibility: "High", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Low", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "High", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Gemini": {
        "Aries": { compatibility: "High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Low", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Very High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Average", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Low", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Very High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Very High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Low", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Average", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Cancer": {
        "Aries": { compatibility: "Low", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Average", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Very High", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Average", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "High", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Low", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Very High", strengths: ["Passionate", "Loyal"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Low", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Average", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Low", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Very High", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Leo": {
        "Aries": { compatibility: "Very High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Average", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Average", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Very High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Low", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Very High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Average", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Low", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Virgo": {
        "Aries": { compatibility: "Average", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Very High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Low", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "High", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Low", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Very High", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Average", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "High", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Low", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Very High", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Low", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Average", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Libra": {
        "Aries": { compatibility: "High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Average", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Very High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Low", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Average", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Very High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Average", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Very High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Low", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Scorpio": {
        "Aries": { compatibility: "Low", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Low", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Very High", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Low", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "High", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Low", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Very High", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Low", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "High", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Low", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Very High", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Sagittarius": {
        "Aries": { compatibility: "Very High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Low", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Very High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Low", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Very High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Low", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Very High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Average", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Low", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Capricorn": {
        "Aries": { compatibility: "Average", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Low", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Average", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Average", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Very High", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Average", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "High", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Average", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Very High", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Low", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "High", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Aquarius": {
        "Aries": { compatibility: "High", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "Low", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "High", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Low", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "High", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Low", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Very High", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Low", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "High", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "Low", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Very High", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Average", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Pisces": {
        "Aries": { compatibility: "Average", strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { compatibility: "High", strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { compatibility: "Average", strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { compatibility: "Very High", strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { compatibility: "Low", strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { compatibility: "Average", strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { compatibility: "Low", strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { compatibility: "Very High", strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { compatibility: "Low", strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { compatibility: "High", strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { compatibility: "Average", strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { compatibility: "Very High", strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    }
};
