export const zodiacSigns = [
    { sign: "Capricorn",    start: { day: 22, month: 12 }, end: { day: 19, month: 1 } },
    { sign: "Aquarius",     start: { day: 20, month: 1 },  end: { day: 18, month: 2 } },
    { sign: "Pisces",       start: { day: 19, month: 2 },  end: { day: 20, month: 3 } },
    { sign: "Aries",        start: { day: 21, month: 3 },  end: { day: 19, month: 4 } },
    { sign: "Taurus",       start: { day: 20, month: 4 },  end: { day: 20, month: 5 } },
    { sign: "Gemini",       start: { day: 21, month: 5 },  end: { day: 20, month: 6 } },
    { sign: "Cancer",       start: { day: 21, month: 6 },  end: { day: 22, month: 7 } },
    { sign: "Leo",          start: { day: 23, month: 7 },  end: { day: 22, month: 8 } },
    { sign: "Virgo",        start: { day: 23, month: 8 },  end: { day: 22, month: 9 } },
    { sign: "Libra",        start: { day: 23, month: 9 },  end: { day: 22, month: 10 } },
    { sign: "Scorpio",      start: { day: 23, month: 10 }, end: { day: 21, month: 11 } },
    { sign: "Sagittarius",  start: { day: 22, month: 11 }, end: { day: 21, month: 12 } }
];

export const compatibilityTable: { [key: string]: string } = {
    '1,5': 'Highly Compatible',
    '2,6': 'Highly Compatible',
    '3,9': 'Highly Compatible',
    '1,3': 'Moderately Compatible',
    '2,4': 'Moderately Compatible',
    '1,8': 'Less Compatible',
    '2,7': 'Less Compatible'
};

export const zodiacTable = {
    "Aries": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Determined", "Patient"], weaknesses: ["Stubborn", "Possessive"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Loyal", "Protective"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Practical", "Analytical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Taurus": {
        "Aries": { strengths: ["Determined", "Patient"], weaknesses: ["Stubborn", "Possessive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Adaptable", "Outgoing"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Loyal", "Emotional"], weaknesses: ["Moody", "Clingy"] },
        "Leo": { strengths: ["Generous", "Creative"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Overly Critical", "Worrying"] },
        "Libra": { strengths: ["Diplomatic", "Charming"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Loyal"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Adventurous", "Optimistic"], weaknesses: ["Impatient", "Blunt"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Gemini": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Cancer": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Loyal"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Leo": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Virgo": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Libra": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Scorpio": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Sagittarius": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Capricorn": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Aquarius": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    },
    "Pisces": {
        "Aries": { strengths: ["Energetic", "Adventurous"], weaknesses: ["Impulsive", "Competitive"] },
        "Taurus": { strengths: ["Reliable", "Patient"], weaknesses: ["Stubborn", "Materialistic"] },
        "Gemini": { strengths: ["Dynamic", "Versatile"], weaknesses: ["Inconsistent", "Indecisive"] },
        "Cancer": { strengths: ["Emotional", "Loyal"], weaknesses: ["Moody", "Overly Sensitive"] },
        "Leo": { strengths: ["Confident", "Charismatic"], weaknesses: ["Arrogant", "Stubborn"] },
        "Virgo": { strengths: ["Analytical", "Practical"], weaknesses: ["Critical", "Worrying"] },
        "Libra": { strengths: ["Charming", "Diplomatic"], weaknesses: ["Indecisive", "Avoids Confrontation"] },
        "Scorpio": { strengths: ["Passionate", "Resourceful"], weaknesses: ["Jealous", "Secretive"] },
        "Sagittarius": { strengths: ["Optimistic", "Adventurous"], weaknesses: ["Blunt", "Impatient"] },
        "Capricorn": { strengths: ["Disciplined", "Responsible"], weaknesses: ["Pessimistic", "Stubborn"] },
        "Aquarius": { strengths: ["Innovative", "Independent"], weaknesses: ["Aloof", "Unpredictable"] },
        "Pisces": { strengths: ["Compassionate", "Intuitive"], weaknesses: ["Escapist", "Overly Sensitive"] }
    }
};
